# PRODUCTION STREAMLIT CLOUD SECRETS
# Copy this to your Streamlit Cloud app secrets

# CRITICAL: PostgreSQL Database (REQUIRED for user persistence)
DATABASE_URL = "postgresql://username:password@hostname.neon.tech/database_name?sslmode=require"

# API Keys
PERPLEXITY_API_KEY = "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"

# Razorpay Payment Gateway
RAZORPAY_KEY_ID = "rzp_live_gBOm5l3scvXYjP"
RAZORPAY_KEY_SECRET = "ptem0kGjg2xW9zWMcGWp2aJz"

# App Configuration
ENVIRONMENT = "production"
SECRET_KEY = "your-production-secret-key-change-this"

# Feature Flags
ENABLE_ANALYTICS = true
ENABLE_PAYMENTS = true
ENABLE_REPORT_HISTORY = true
ENABLE_WATERMARKS = true

# Optional: Google Analytics
GA4_MEASUREMENT_ID = "your_ga4_measurement_id"
GA4_API_SECRET = "your_ga4_api_secret"
