# Streamlit Secrets Configuration - UPDATED with Payment Fix
# Copy this to your Streamlit Cloud app secrets

# Perplexity API for AI Analysis
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"

# Razorpay Payment Gateway (FIXED CONFIGURATION)
RAZORPAY_KEY_ID = "rzp_live_gBOm5l3scvXYjP"
RAZORPAY_KEY_SECRET = "ptem0kGjg2xW9zWMcGWp2aJz"
RAZORPAY_WEBHOOK_SECRET = "your_webhook_secret_here"

# Database Configuration
DATABASE_URL = "sqlite:///data/app.db"

# App Configuration
ENVIRONMENT = "production"
SECRET_KEY = "your-secret-key-change-in-production"
APP_URL = "https://resume-jd-analyze.streamlit.app"

# Analytics (Optional)
GOOGLE_ANALYTICS_ID = "your_ga_id_here"

# Email Configuration (Optional)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USERNAME = "your_email@gmail.com"
SMTP_PASSWORD = "your_app_password"

# Feature Flags
ENABLE_ANALYTICS = true
ENABLE_PAYMENTS = true
ENABLE_REPORT_HISTORY = true
ENABLE_WATERMARKS = true