# Streamlit Cloud Secrets Template
# Copy this to your Streamlit Cloud app secrets

# Required API Keys
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"
RAZORPAY_KEY_SECRET = "your_razorpay_secret_key_here"
SECRET_KEY = "your_secret_key_for_sessions_here"

# Optional Configuration
RAZORPAY_KEY_ID = "your_razorpay_key_id_here"
DATABASE_URL = "sqlite:///data/app.db"
ENVIRONMENT = "production"

# Instructions:
# 1. Go to your Streamlit Cloud app settings
# 2. Navigate to the "Secrets" section
# 3. Copy the above variables (without comments)
# 4. Replace the placeholder values with your actual keys
# 5. Save the secrets configuration
