# Copy this content to Streamlit Cloud Secrets
# Go to Advanced Settings → Secrets when deploying

# AI Service API Key
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"

# Razorpay Payment Gateway (Your live credentials)
RAZORPAY_KEY_ID = "rzp_live_gBOm5l3scvXYjP"
RAZORPAY_KEY_SECRET = "your_razorpay_secret_key_here"
RAZORPAY_WEBHOOK_SECRET = "your_webhook_secret_here"

# Application Settings
ENVIRONMENT = "production"
APP_URL = "https://your-app-name.streamlit.app"
SECRET_KEY = "your-secret-key-for-sessions"

# Database (SQLite for Streamlit Cloud)
DATABASE_URL = "sqlite:///data/app.db"

# Optional: Email settings (for notifications)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "your-email@gmail.com"
SMTP_PASSWORD = "your-app-password"