
[server]
headless = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "light"

# Cloud-friendly settings
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
