# Streamlit Cloud Secrets Template
# Add these to your Streamlit Cloud app settings

[secrets]
DATABASE_URL = "your_postgresql_database_url"
RAZORPAY_KEY_ID = "rzp_live_your_key_id_here"
RAZORPAY_KEY_SECRET = "your_razorpay_key_secret_here"

# Optional
RAZORPAY_WEBHOOK_SECRET = "your_webhook_secret_here"
